# ABOUTME: SwiftLint configuration for code quality and consistency
# ABOUTME: Enforces Swift best practices and catches common mistakes

excluded:
  - .build
  - Tests/MusicAssistantKitTests/Mocks

# Rule Configuration
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo  # Allow TODO comments
  - line_length  # SwiftFormat handles this
  - trailing_comma  # SwiftFormat handles this
  - blanket_disable_command  # Allow disabling rules for comprehensive test files

# Custom rule values
file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 40
  error: 100

type_body_length:
  warning: 200
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - uri

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Allow force unwrapping in tests
force_unwrapping:
  severity: error

# Reporter
reporter: "xcode"
